version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234567Aa"
      POSTGRES_DB: MangaUpdater
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: migrations.Dockerfile
    depends_on:
      db:
        condition: service_healthy
  mangaupdater:
    container_name: mangaupdater
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db:5432; Database=MangaUpdater; User Id=postgres; Password=1234567Aa;
      - Issuer=http://localhost
      - Audience=audiencehere
      - ApiKey=yourapikeyhereyourapikeyhereyourapikeyhereyourapikeyhereyourapikeyhere
      - HangfireLogin=Admin
      - HangfirePassword=123456789
    depends_on:
      - migrations
